//
//  UIFont+MRAdditions.swift
//
//  Generated by Zeplin on 5/23/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func mrTextStyleFont() -> UIFont? {
		return UIFont(name: "Helvetica-Bold", size: 80.0)
	}
    
    class func mrTextStyle2Font() -> UIFont? {
        return UIFont(name: "PingFangTC-Medium", size: 20.0)
    }
    
    class func mrTextStyle3Font() -> UIFont {
        return UIFont.systemFontOfSize(24.0, weight: UIFontWeightBold)
    }

    class func mrTextStyle4Font() -> UIFont {
        return UIFont.systemFontOfSize(10.0, weight: UIFontWeightRegular)
    }
    
    class func mrTextStyle5Font() -> UIFont? {
        return UIFont(name: "Helvetica", size: 50.0)
    }
    
    class func mrTextStyle6Font() -> UIFont? {
        return UIFont(name: "Helvetica", size: 20.0)
    }

    class func mrTextStyle7Font() -> UIFont {
        return UIFont.systemFontOfSize(24.0, weight: UIFontWeightMedium)
    }
    
    class func mrTextStyle8Font() -> UIFont {
        return UIFont.systemFontOfSize(80.0, weight: UIFontWeightBold)
    }
    
    class func mrTextStyle9Font() -> UIFont {
        return UIFont.systemFontOfSize(30.0, weight: UIFontWeightRegular)
    }


    class func mrTextStyle10Font() -> UIFont {
        return UIFont.systemFontOfSize(20.0, weight: UIFontWeightMedium)
    }

	class func mrTextStyle11Font() -> UIFont {
		return UIFont.systemFontOfSize(24.0, weight: UIFontWeightMedium)
	}

	class func mrTextStyle12Font() -> UIFont {
		return UIFont.systemFontOfSize(12.0, weight: UIFontWeightRegular)
	}

    class func mrTextStyle13Font() -> UIFont {
        return UIFont.systemFontOfSize(17.0, weight: UIFontWeightSemibold)
    }
    
    class func mrTextStyle14Font() -> UIFont {
        return UIFont.systemFontOfSize(80.0, weight: UIFontWeightBold)
    }
    
    class func asiTextStyle15Font() -> UIFont {
        return UIFont.systemFontOfSize(30.0, weight: UIFontWeightRegular)
    }
    
    class func asiTextStyle16Font() -> UIFont {
        return UIFont.systemFontOfSize(30.0, weight: UIFontWeightMedium)
    }
    
    // no 17
    
    class func asiTextStyle18Font() -> UIFont {
        return UIFont.systemFontOfSize(17.0, weight: UIFontWeightRegular)
    }
    
    // 19
    
    class func textStyle20Font() -> UIFont {
        return UIFont.systemFontOfSize(12.0, weight: UIFontWeightRegular)
    }
    
    class func textStyle21Font() -> UIFont {
        return UIFont.systemFontOfSize(60.0, weight: UIFontWeightBold)
    }
    
    class func textStyle22Font() -> UIFont {
        return UIFont.systemFontOfSize(14.0, weight: UIFontWeightRegular)
    }
    
    class func textStyle23Font() -> UIFont {
        return UIFont.systemFontOfSize(12.0, weight: UIFontWeightRegular)
    }
    
    class func textStyle24Font() -> UIFont {
        return UIFont.systemFontOfSize(20.0, weight: UIFontWeightRegular)
    }
    
    // 25
    
    class func textStyle26Font() -> UIFont {
        return UIFont.systemFontOfSize(10.0, weight: UIFontWeightLight)
    }
    
    class func textStyle27Font() -> UIFont {
        return UIFont.systemFontOfSize(24.0, weight: UIFontWeightRegular)
    }
    
}
